service: some-api

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1

functions:
  hello:
    handler: rest-api/greeting/get/handler.hello
    events:
      - http:
          path: /greeting
          method: get
    environment:
      PERSON_TO_SAY_HELLO_TO: Scott